// Turns CHANGELOG.md, which release-please maintains, into the JSON the
// changelog page reads (#813). The page makes no request to GitHub: it
// fetches this one same-origin file, so it also lists exactly the releases
// the running binary was built from.
//
//   bun scripts/changelog-json.ts            # writes web/static/changelog.json
//
// Output is a build artefact (gitignored), regenerated by `bun run build` in
// web/. CHANGELOG.md stays the one source of truth.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface Release {
  version: string;
  // YYYY-MM-DD, as release-please writes it.
  date: string;
  // The release's page on its forge, derived from the compare link in the
  // heading. Empty when the heading has no link.
  url: string;
  // The markdown under the heading, as release-please wrote it.
  notes: string;
}

// "## [0.115.0](https://github.com/o/r/compare/v0.114.0...v0.115.0) (2026-10-03)"
// and, for a first release, "## 0.1.0 (2026-09-01)".
const HEADING =
  /^## \[?(\d+\.\d+\.\d+[^\]\s)]*)\]?(?:\(([^)]*)\))?\s*\((\d{4}-\d{2}-\d{2})\)\s*$/;

function releaseUrl(compareUrl: string | undefined, version: string): string {
  const match = compareUrl?.match(
    /^(https?:\/\/[^/]+\/[^/]+\/[^/]+)\/compare\//,
  );
  return match ? `${match[1]}/releases/tag/v${version}` : '';
}

export function parseChangelog(markdown: string): Release[] {
  const releases: Release[] = [];
  let current: { release: Release; lines: string[] } | null = null;

  const finish = () => {
    if (!current) return;
    current.release.notes = current.lines.join('\n').trim();
    releases.push(current.release);
    current = null;
  };

  for (const line of markdown.split('\n')) {
    if (line.startsWith('## ')) {
      finish();
      const match = line.match(HEADING);
      if (match) {
        const [, version, compare, date] = match;
        current = {
          release: {
            version,
            date,
            url: releaseUrl(compare, version),
            notes: '',
          },
          lines: [],
        };
      }
      continue;
    }
    current?.lines.push(line);
  }
  finish();

  return releases;
}

const here = dirname(fileURLToPath(import.meta.url));

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = join(here, '..');
  const releases = parseChangelog(
    readFileSync(join(root, 'CHANGELOG.md'), 'utf8'),
  );
  if (releases.length === 0) {
    console.error('changelog-json: no release headings found in CHANGELOG.md');
    process.exit(1);
  }
  const out = join(root, 'web', 'static', 'changelog.json');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, `${JSON.stringify({ releases })}\n`);
  console.log(`changelog-json: ${releases.length} releases -> ${out}`);
}
